sudo: required
dest: precise
language: java
jdk:
  - oraclejdk9
  - oraclejdk8
  - oraclejdk7
  - openjdk7

cache:
  directories:
    - $HOME/.m2

before_install:
  - export MAVEN_SKIP_RC=true

install: true

script:
  - mvn xml:check-format -P xml-check-format
  - mvn formatter:validate -P common-libs
  - mvn -U clean install
  - mvn -U -P common-libs jacoco:report coveralls:report
