sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - ./mvn-build-all.sh clean install jacoco:report
  - if [[ $TRAVIS_JDK_VERSION != "openjdk6" ]]; then mvn -U coveralls:report -f terasoluna-gfw-parent/pom.xml; fi